/*
 * This file is generated by jOOQ.
 */
package djma.db.jooq;


import djma.db.jooq.tables.Contact;
import djma.db.jooq.tables.Kvstore;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.contact</code>.
     */
    public static final Contact CONTACT = Contact.CONTACT;

    /**
     * The table <code>public.kvstore</code>.
     */
    public static final Kvstore KVSTORE = Kvstore.KVSTORE;
}
