/*
 * This file is generated by jOOQ.
 */
package djma.db.jooq.tables.records;


import djma.db.jooq.tables.Kvstore;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KvstoreRecord extends UpdatableRecordImpl<KvstoreRecord> implements Record3<String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.kvstore.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.kvstore.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.kvstore.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.kvstore.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.kvstore.lastModified</code>.
     */
    public void setLastmodified(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.kvstore.lastModified</code>.
     */
    public LocalDateTime getLastmodified() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Kvstore.KVSTORE.KEY;
    }

    @Override
    public Field<String> field2() {
        return Kvstore.KVSTORE.VALUE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Kvstore.KVSTORE.LASTMODIFIED;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public LocalDateTime component3() {
        return getLastmodified();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public LocalDateTime value3() {
        return getLastmodified();
    }

    @Override
    public KvstoreRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public KvstoreRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public KvstoreRecord value3(LocalDateTime value) {
        setLastmodified(value);
        return this;
    }

    @Override
    public KvstoreRecord values(String value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KvstoreRecord
     */
    public KvstoreRecord() {
        super(Kvstore.KVSTORE);
    }

    /**
     * Create a detached, initialised KvstoreRecord
     */
    public KvstoreRecord(String key, String value, LocalDateTime lastmodified) {
        super(Kvstore.KVSTORE);

        setKey(key);
        setValue(value);
        setLastmodified(lastmodified);
    }
}
